# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ae5280a35ee4482035560ccf41a09d10c35aa097b70595177fb49d1a70be9f1fa224c2850b605a5a7fa38c3227c539da5c39fd84e539228c7b48460fd5d2fd8

test:
  secret_key_base: ea2c5ad0b6e68bf44bc4c710fd6e84d457f4954f77be29ede1dbee10d8854e87a9c8ada0f1833c2d5366843e1a0fa078d02786970c84a8ee7412e977ea9e32b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
